Fix 352 url
bird-house/pywps pull request #2
Opened 2018-07-05 17:29 UTC by huard

# Overview

Refactoring of the IOHandler class to handle urls. 
I got carried away here and refactored the class instead of adding a bunch of `if` clauses all over the place. The main difference from the previous implementation is that once a ComplexInput sets a property (file, data, url, stream), it won't be possible to set another attribute. Other properties can however be read, that is 

```
h = IOHandler()
h.data = 'test'
f.file = 'test.txt' # will raise an error but
print(h.file) will work. 
```
So URLs can now be set and won't trigger a download unless explicitly requested by accessing the `file` attribute. 
```
h = IOHandler()
h.url = 'http://...' # Mixes the instance with the UrlHandler class.
h.file # Fetches the data and copies to a local file
h.data # Reads the content from h.file
```

# Related Issue / Discussion
Email threads on pywps-dev
https://github.com/geopython/pywps/issues/352

# Additional Information
- This will help support opendap mimetype. 
- birdhouse/master is behind the upstream repo. 
- Very few modifications were done to tests, so these changes should be backward compatible, except for cases where IOhandler instances set different properties (which is probably a bad idea anyway). 

# Contribution Agreement

(as per https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to PyWPS. I confirm that my contributions to PyWPS will be compatible with the PyWPS license guidelines at the time of contribution.
- [ ] I have already previously agreed to the PyWPS Contributions and Licensing Guidelines

2018-07-10 13:27 UTC, cehbrecht commented
@huard did you make this PR intentionally to the birdhouse fork? Should it not be merged to the pywps master?

2018-07-23 13:41 UTC, huard commented
Yes, but I'd like you to take a look before I make an official PR to the repo to make sure I'm not doing something stupid.

2018-08-03 15:05 UTC, cehbrecht commented
@huard I have merged this PR to a new branch:
https://github.com/bird-house/pywps/tree/dev-issue-352-url 

I have fixed pep8 and the tests (python 2/3 encoding issues).

2018-08-03 15:14 UTC, cehbrecht commented
@huard I would set config defaults in the `configuration` module. For tests we might want a special config ... I think you tried this in PR #1. `/tmp` as `allowedinputpaths` does not work on macOS (using `/var/`):

https://github.com/bird-house/pywps/blob/4ba73cfdc0e29d70784cdb7ed486f9e35d78c0ab/pywps/inout/basic.py#L170

2018-08-03 15:51 UTC, cehbrecht commented
@huard I tried this PR with Emu and my `chomsky` process complains:
```
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/pingu/Documents/GitHub/birdhouse/emu/emu/processes/wps_chomsky.py", line 159, in _handler
    response.outputs['output'].file = fout.name
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/inout/basic.py", line 277, in fset
    setattr(s, kls.prop, value)
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/inout/basic.py", line 295, in file
    self._validate_file_input(path)
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/inout/basic.py", line 370, in _validate_file_input
    raise FileURLNotSupported()
pywps.exceptions.FileURLNotSupported: 400 FileURLNotSupported: File URL not supported as input.
```

The `allowedinputpath` check also runs for outputs ... probably useful. We need to make sure that pywps temp folders are *always* allowed.

2018-08-03 15:56 UTC, cehbrecht commented
@huard ... I allowed all outputs but I run then into another exception, something went wrong with setting the outputs:
```
2018-08-03 17:53:43,280] [ERROR] line=229 module=Process Process error: wps_chomsky.py._handler Line 159 [Errno 2] No such file or directory: '/Users/pingu/Documents/GitHub/birdhouse/emu/out.txt' -> '/var/folders/5f/t661zdnd181ck1dv429s4p8r0000gn/T/pywps_process_pu8rotdd/out.txt'
2018-08-03 17:53:43,287] [ERROR] line=45 module=exceptions Exception: code: 400, locator: Writing Response Document failed with : [Errno 2] No such file or directory: '/var/folders/5f/t661zdnd181ck1dv429s4p8r0000gn/T/pywps_process_pu8rotdd/out.txt', description: 
Traceback (most recent call last):
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/pingu/Documents/GitHub/birdhouse/emu/emu/processes/wps_chomsky.py", line 159, in _handler
    response.outputs['output'].file = fout.name
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/inout/basic.py", line 277, in fset
    setattr(s, kls.prop, value)
  File "/Users/pingu/Documents/GitHub/birdhouse/pywps/pywps/inout/basic.py", line 297, in file
    os.symlink(path, self._tmpfilename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pingu/Documents/GitHub/birdhouse/emu/out.txt' -> '/var/folders/5f/t661zdnd181ck1dv429s4p8r0000gn/T/pywps_process_pu8rotdd/out.txt'

```

2018-08-03 16:03 UTC, cehbrecht commented
@huard This PR comes with a lot of code changes. Though they look meaningful I can't oversee them. We should also ask for a review by the original pywps code authors (Jachym and Luis).

In this PR you have the following:
1. clean up of code
2. introducing a new URL property
3. refactoring of IOHandler.

It might be easier to get this into pywps with 2-3 PRs.

2018-08-03 16:05 UTC, cehbrecht requested changes
Please split this PR in 2-3 PRs and make them to the original pywps repo for review. See comments.

2018-08-13 13:51 UTC, huard commented
Thanks for the review, will do 1, 3, 2.

2018-08-14 12:27 UTC, huard commented
Not clear to me what I should do about the allowed input path configuration. Should the test loader modify the config ?

2018-08-14 12:37 UTC, huard commented
I can't reproduce the bug you see with emu on linux. I suspect it has something to do with the allowedinputpath. Should I set the default to outputpath ?

2018-08-14 12:40 UTC, huard commented
Wait, I've done a pull on master and now I get the same error. Investigating.

2018-08-14 18:28 UTC, huard commented
So I think the bug has to do with the fact that I'm using the same code for inputs and outputs. If I restrict the file setter code to ComplexInput, it works. Now it's not clear to me how I should handle outputs.

2018-08-15 13:51 UTC, cehbrecht commented
Looks like you figured it out :)

2018-08-15 14:37 UTC, huard commented
Yes an no. I simplified the Handler classes by removing the code that reproduced the logic in app/Service.py and which was specific to input handling. It makes the PR simpler and less error prone. I still think the Service.py logic could be moved into the ComplexInput class, but that will be for another day.

2018-10-01 08:59 UTC, cehbrecht commented
Add to pywps: https://github.com/geopython/pywps/issues/352

Closing now.

2018-10-01 08:59 UTC, closed without merging